import 'package:flutter/material.dart';
import 'package:flutterapp/salbaapp/generatedwolkietolkiewidget/generated/GeneratedEllipse4Widget2.dart';
import 'package:flutterapp/salbaapp/generatedwolkietolkiewidget/generated/GeneratedIcon1Widget.dart';
import 'package:flutterapp/salbaapp/generatedwolkietolkiewidget/generated/GeneratedSalna1Widget1.dart';
import 'package:flutterapp/salbaapp/generatedwolkietolkiewidget/generated/GeneratedIcon2Widget.dart';
import 'package:flutterapp/salbaapp/generatedwolkietolkiewidget/generated/GeneratedMaskGroupWidget.dart';
import 'package:flutterapp/salbaapp/generatedwolkietolkiewidget/generated/GeneratedComponentWidget6.dart';
import 'package:flutterapp/salbaapp/generatedwolkietolkiewidget/generated/GeneratedRescuerWidget.dart';
import 'package:flutterapp/salbaapp/generatedwolkietolkiewidget/generated/GeneratedRectangle3Widget6.dart';
import 'package:flutterapp/salbaapp/generatedwolkietolkiewidget/generated/GeneratedRectangle2Widget6.dart';
import 'package:flutterapp/salbaapp/generatedwolkietolkiewidget/generated/GeneratedEllipse8Widget.dart';
import 'package:flutterapp/salbaapp/generatedwolkietolkiewidget/generated/GeneratedRectangle1Widget9.dart';
import 'package:flutterapp/salbaapp/generatedwolkietolkiewidget/generated/GeneratedJuandelaCruzWidget.dart';
import 'package:flutterapp/salbaapp/generatedwolkietolkiewidget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/salbaapp/generatedwolkietolkiewidget/generated/GeneratedSalmaorenh1Widget.dart';
import 'package:flutterapp/salbaapp/generatedwolkietolkiewidget/generated/GeneratedEllipse7Widget.dart';

/* Frame Wolkie Tolkie
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWolkieTolkieWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 502.0,
                child: GeneratedRectangle2Widget6(),
              ),
              Positioned(
                left: 180.0,
                top: 44.087158203125,
                right: null,
                bottom: null,
                width: 213.3863067626953,
                height: 213.3863067626953,
                child: GeneratedMaskGroupWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 502.0,
                child: GeneratedRectangle3Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 536.0,
                child: GeneratedRectangle1Widget9(),
              ),
              Positioned(
                left: 31.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 72.0,
                child: GeneratedSalna1Widget1(),
              ),
              Positioned(
                left: 338.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 42.0,
                child: GeneratedIcon2Widget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 48.0,
                height: 42.0,
                child: TransformHelper.translate(
                    x: 48.00, y: -187.00, z: 0, child: GeneratedIcon1Widget()),
              ),
              Positioned(
                left: 117.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 23.0,
                child: GeneratedRescuerWidget(),
              ),
              Positioned(
                left: 117.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 25.0,
                child: GeneratedJuandelaCruzWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 315.0,
                child: GeneratedEllipse6Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 22.0,
                child: GeneratedComponentWidget6(),
              ),
              Positioned(
                left: 77.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 261.0,
                child: GeneratedEllipse7Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 158.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 47.0,
                child: GeneratedSalmaorenh1Widget(),
              ),
              Positioned(
                left: 104.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 206.0,
                height: 206.0,
                child: GeneratedEllipse8Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 736.0,
                child: GeneratedEllipse4Widget2(),
              )
            ]),
      ),
    ));
  }
}
