import 'package:flutter/material.dart';
import 'package:flutterapp/salbaapp/generatedmapuaevacuationcenterwidget/generated/GeneratedYouth1Widget.dart';
import 'package:flutterapp/salbaapp/generatedmapuaevacuationcenterwidget/generated/GeneratedComponentWidget.dart';
import 'package:flutterapp/salbaapp/generatedmapuaevacuationcenterwidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/salbaapp/generatedmapuaevacuationcenterwidget/generated/GeneratedCurrentNumberofEvacueesWidget.dart';
import 'package:flutterapp/salbaapp/generatedmapuaevacuationcenterwidget/generated/Generated63285271134Widget.dart';
import 'package:flutterapp/salbaapp/generatedmapuaevacuationcenterwidget/generated/GeneratedEmergencycall21Widget.dart';
import 'package:flutterapp/salbaapp/generatedmapuaevacuationcenterwidget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/salbaapp/generatedmapuaevacuationcenterwidget/generated/GeneratedLifejacket1Widget.dart';
import 'package:flutterapp/salbaapp/generatedmapuaevacuationcenterwidget/generated/GeneratedSalbaHeaderSmall1Widget.dart';
import 'package:flutterapp/salbaapp/generatedmapuaevacuationcenterwidget/generated/GeneratedEvacuationCapacityWidget.dart';
import 'package:flutterapp/salbaapp/generatedmapuaevacuationcenterwidget/generated/GeneratedBACKWidget2.dart';
import 'package:flutterapp/salbaapp/generatedmapuaevacuationcenterwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/salbaapp/generatedmapuaevacuationcenterwidget/generated/GeneratedNotheader1Widget.dart';
import 'package:flutterapp/salbaapp/generatedmapuaevacuationcenterwidget/generated/Generated658MurallaStIntramurosManila1002MetroManilaWidget.dart';
import 'package:flutterapp/salbaapp/generatedmapuaevacuationcenterwidget/generated/GeneratedMapaUniversityWidget.dart';
import 'package:flutterapp/salbaapp/generatedmapuaevacuationcenterwidget/generated/Generated83Widget.dart';
import 'package:flutterapp/salbaapp/generatedmapuaevacuationcenterwidget/generated/GeneratedEmergencyHotlineWidget.dart';
import 'package:flutterapp/salbaapp/generatedmapuaevacuationcenterwidget/generated/Generated120Widget.dart';

/* Frame Mapua-Evacuation Center
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMapuaEvacuationCenterWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 100.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 275.0,
                height: 41.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 100.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 275.0,
                height: 41.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 100.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 275.0,
                height: 41.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 35.5869140625,
                top: null,
                right: null,
                bottom: null,
                width: 50.41604232788086,
                height: 54.26755905151367,
                child: TransformHelper.translate(
                    x: 0.00, y: -17.87, z: 0, child: GeneratedYouth1Widget()),
              ),
              Positioned(
                left: 39.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 60.0,
                child:
                    Generated658MurallaStIntramurosManila1002MetroManilaWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 55.0,
                child: GeneratedMapaUniversityWidget(),
              ),
              Positioned(
                left: 0.0,
                top: -3.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 721.0,
                child: GeneratedSalbaHeaderSmall1Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 68.0,
                child: GeneratedEmergencycall21Widget(),
              ),
              Positioned(
                left: 227.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 36.0,
                child: Generated120Widget(),
              ),
              Positioned(
                left: 227.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 36.0,
                child: Generated83Widget(),
              ),
              Positioned(
                left: 176.0,
                top: 534.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 33.0,
                child: Generated63285271134Widget(),
              ),
              Positioned(
                left: 176.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 20.0,
                child: GeneratedEvacuationCapacityWidget(),
              ),
              Positioned(
                left: 154.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 20.0,
                child: GeneratedCurrentNumberofEvacueesWidget(),
              ),
              Positioned(
                left: 180.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 20.0,
                child: GeneratedEmergencyHotlineWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 421.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 47.0,
                child: GeneratedLifejacket1Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 21.0,
                child: GeneratedBACKWidget2(),
              ),
              Positioned(
                left: 480.0,
                top: 938.0,
                right: null,
                bottom: null,
                width: 483.0000305175781,
                height: 313.9999694824219,
                child: GeneratedNotheader1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 22.0,
                child: GeneratedComponentWidget(),
              )
            ]),
      ),
    ));
  }
}
