import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/salbaapp/generatedresidenciaevacuationwidget/generated/Generated128Widget.dart';
import 'package:flutterapp/salbaapp/generatedresidenciaevacuationwidget/generated/GeneratedYouth1Widget1.dart';
import 'package:flutterapp/salbaapp/generatedresidenciaevacuationwidget/generated/GeneratedBACKWidget4.dart';
import 'package:flutterapp/salbaapp/generatedresidenciaevacuationwidget/generated/Generated0285231349Widget.dart';
import 'package:flutterapp/salbaapp/generatedresidenciaevacuationwidget/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/salbaapp/generatedresidenciaevacuationwidget/generated/GeneratedEmergencyHotlineWidget1.dart';
import 'package:flutterapp/salbaapp/generatedresidenciaevacuationwidget/generated/GeneratedLifejacket1Widget1.dart';
import 'package:flutterapp/salbaapp/generatedresidenciaevacuationwidget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/salbaapp/generatedresidenciaevacuationwidget/generated/GeneratedNotheader2Widget.dart';
import 'package:flutterapp/salbaapp/generatedresidenciaevacuationwidget/generated/GeneratedRectangle1Widget2.dart';
import 'package:flutterapp/salbaapp/generatedresidenciaevacuationwidget/generated/GeneratedSalbaHeaderSmall1Widget1.dart';
import 'package:flutterapp/salbaapp/generatedresidenciaevacuationwidget/generated/GeneratedResidencia729Widget.dart';
import 'package:flutterapp/salbaapp/generatedresidenciaevacuationwidget/generated/GeneratedComponentWidget1.dart';
import 'package:flutterapp/salbaapp/generatedresidenciaevacuationwidget/generated/GeneratedEmergencycall21Widget1.dart';
import 'package:flutterapp/salbaapp/generatedresidenciaevacuationwidget/generated/Generated150Widget.dart';
import 'package:flutterapp/salbaapp/generatedresidenciaevacuationwidget/generated/GeneratedCurrentNumberofEvacueesWidget1.dart';
import 'package:flutterapp/salbaapp/generatedresidenciaevacuationwidget/generated/Generated729StaPotenciaStIntramurosManilaNearSanAgustinChurchWid.dart';
import 'package:flutterapp/salbaapp/generatedresidenciaevacuationwidget/generated/GeneratedEvacuationCapacityWidget1.dart';

/* Frame Residencia Evacuation
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedResidenciaEvacuationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 100.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 275.0,
                height: 41.0,
                child: GeneratedRectangle1Widget2(),
              ),
              Positioned(
                left: 100.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 275.0,
                height: 41.0,
                child: GeneratedRectangle3Widget1(),
              ),
              Positioned(
                left: 100.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 275.0,
                height: 41.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 35.5869140625,
                top: null,
                right: null,
                bottom: null,
                width: 50.41604232788086,
                height: 54.26755905151367,
                child: TransformHelper.translate(
                    x: 0.00, y: -17.87, z: 0, child: GeneratedYouth1Widget1()),
              ),
              Positioned(
                left: 39.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 60.0,
                child:
                    Generated729StaPotenciaStIntramurosManilaNearSanAgustinChurchWid(),
              ),
              Positioned(
                left: 37.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 45.0,
                child: GeneratedResidencia729Widget(),
              ),
              Positioned(
                left: 0.0,
                top: -3.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 721.0,
                child: GeneratedSalbaHeaderSmall1Widget1(),
              ),
              Positioned(
                left: 27.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 68.0,
                child: GeneratedEmergencycall21Widget1(),
              ),
              Positioned(
                left: 227.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 36.0,
                child: Generated150Widget(),
              ),
              Positioned(
                left: 227.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 36.0,
                child: Generated128Widget(),
              ),
              Positioned(
                left: 180.0,
                top: 534.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 33.0,
                child: Generated0285231349Widget(),
              ),
              Positioned(
                left: 176.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 20.0,
                child: GeneratedEvacuationCapacityWidget1(),
              ),
              Positioned(
                left: 154.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 20.0,
                child: GeneratedCurrentNumberofEvacueesWidget1(),
              ),
              Positioned(
                left: 180.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 20.0,
                child: GeneratedEmergencyHotlineWidget1(),
              ),
              Positioned(
                left: 39.0,
                top: 421.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 47.0,
                child: GeneratedLifejacket1Widget1(),
              ),
              Positioned(
                left: 15.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 21.0,
                child: GeneratedBACKWidget4(),
              ),
              Positioned(
                left: 480.0,
                top: 929.0,
                right: null,
                bottom: null,
                width: 483.0000305175781,
                height: 313.9999694824219,
                child: GeneratedNotheader2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 22.0,
                child: GeneratedComponentWidget1(),
              )
            ]),
      ),
    ));
  }
}
